# Generated by Django 5.2.13 on 2026-04-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('url', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manba')),
                ('published_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sanasi')),
                ('is_summary', models.BooleanField(default=False)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('last_summarize_attempt', models.DateTimeField(blank=True, null=True)),
                ('summarize_failed_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Barcha Yangiliklar',
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Ikonka (Emoji)')),
                ('keywords', models.TextField(help_text="Vergul bilan ajratilgan kalit so'zlar (masalan: siyosat, jahon). Avtomatik ulash uchun ishlatiladi.", verbose_name="Kalit so'zlar")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary_rel', serialize=False, to='news.article')),
                ('summary_text', models.TextField()),
            ],
            options={
                'db_table': 'Summary',
                'managed': False,
            },
        ),
    ]
